package Interface;

import esteganografia_simple.Esteganos;
import esteganografia_simple.paint;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

public class InterCifra extends javax.swing.JFrame {

    BufferedImage foto;
    paint minhapaint = new paint();
    Esteganos esteganos = new Esteganos();

    /**
     * Cria formulário interfaz
     */
    public InterCifra() {
        initComponents();
        this.setTitle("Esteganografia");
        //adiciona o componente minhapaint
        this.setLocationRelativeTo(null);
        jPanel1.add(minhapaint);
        minhapaint.updateUI();
        this.cmdSalvarImagem.setEnabled(false);
        this.cmdOcultarMensagem.setEnabled(false);
        this.cmdVerMensagem.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmdAbrirImagem = new javax.swing.JButton();
        cmdOcultarMensagem = new javax.swing.JButton();
        cmdSalvarImagem = new javax.swing.JButton();
        cmdVerMensagem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMensagem = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButtonCifrar = new javax.swing.JButton();
        jButtonDecifrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaMensagemEmClaro = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMensagemDecifrada = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaMensagemCifrada = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        cmdAbrirImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder_picture.png"))); // NOI18N
        cmdAbrirImagem.setText("Abrir Imagem");
        cmdAbrirImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAbrirImagemActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAbrirImagem);

        cmdOcultarMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/key1.png"))); // NOI18N
        cmdOcultarMensagem.setText("Ocultar Mensagem");
        cmdOcultarMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOcultarMensagemActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOcultarMensagem);

        cmdSalvarImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_save.png"))); // NOI18N
        cmdSalvarImagem.setText("Salvar Imagem");
        cmdSalvarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalvarImagemActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSalvarImagem);

        cmdVerMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock_open.png"))); // NOI18N
        cmdVerMensagem.setText("Ver Mensagem");
        cmdVerMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerMensagemActionPerformed(evt);
            }
        });
        jPanel2.add(cmdVerMensagem);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensagem Oculta   "));
        jPanel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jtMensagem.setColumns(20);
        jtMensagem.setRows(5);
        jScrollPane2.setViewportView(jtMensagem);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cifra de Cesar"));
        jPanel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jButtonCifrar.setText("Cifrar");
        jButtonCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCifrarActionPerformed(evt);
            }
        });

        jButtonDecifrar.setText("Decifrar");
        jButtonDecifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecifrarActionPerformed(evt);
            }
        });

        jTextAreaMensagemEmClaro.setColumns(20);
        jTextAreaMensagemEmClaro.setRows(5);
        jScrollPane3.setViewportView(jTextAreaMensagemEmClaro);

        jTextAreaMensagemDecifrada.setColumns(20);
        jTextAreaMensagemDecifrada.setRows(5);
        jScrollPane4.setViewportView(jTextAreaMensagemDecifrada);

        jTextAreaMensagemCifrada.setColumns(20);
        jTextAreaMensagemCifrada.setRows(5);
        jScrollPane5.setViewportView(jTextAreaMensagemCifrada);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mensagem em Claro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mensagem Cifrada");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Mensagem Decifrada");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDecifrar)
                    .addComponent(jButtonCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCifrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDecifrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Mensagem Oculta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAbrirImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbrirImagemActionPerformed
        if (minhapaint.Abrir_Imagem()) {
            this.cmdOcultarMensagem.setEnabled(true);
            this.cmdVerMensagem.setEnabled(true);
            this.jtMensagem.setText("");
            jPanel1.setPreferredSize(minhapaint.getTamanho());
            minhapaint.updateUI();
        }
    }//GEN-LAST:event_cmdAbrirImagemActionPerformed

    private void cmdOcultarMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOcultarMensagemActionPerformed
        //oculta a mensagem na imagem
        esteganos.OcultarMensagem(minhapaint.getFoto(), jTextAreaMensagemCifrada.getText());
        //repete a imagem da tela
        minhapaint.setFoto(esteganos.getFoto());
        //desabilita o botão
        cmdOcultarMensagem.setEnabled(false);
        cmdSalvarImagem.setEnabled(true);
        JOptionPane.showMessageDialog(null, "A mensagem foi ocultada na imagem");
    }//GEN-LAST:event_cmdOcultarMensagemActionPerformed

    private void cmdSalvarImagemActionPerformed(java.awt.event.ActionEvent evt) {
        minhapaint.guardar_imagem(esteganos.getFoto());
        cmdSalvarImagem.setEnabled(false);
    }

    private void cmdVerMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerMensagemActionPerformed
        this.jtMensagem.setText("");
        this.jtMensagem.setText(esteganos.getMensagemToImage(minhapaint.getFoto()));
    }//GEN-LAST:event_cmdVerMensagemActionPerformed

    private void jButtonCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCifrarActionPerformed
        
        
        int chave=7;
        String texto = this.jTextAreaMensagemEmClaro.getText();
	int tamanhoTexto = texto.length();
        StringBuilder textoCifrado = new StringBuilder();
        
		// Criptografa cada caracter por vez 
		for(int c=0; c < tamanhoTexto; c++){
			// Transforma o caracter em codigo ASCII e faz a criptografia
			int letraCifradaASCII = ((int) texto.charAt(c)) + chave;
			
			// Verifica se o codigo ASCII esta no limite dos caracteres imprimiveis
			while(letraCifradaASCII > 126)
				letraCifradaASCII -= 94;

			// Transforma codigo ASCII criptografado em caracter ao novo texto
			textoCifrado.append((char)letraCifradaASCII);
                        
                }
        //converte a mensagem cifrada para String
        String mensagemCifrada = textoCifrado.toString();
        //joga a mensagem cifrada na Area de Texto Mensagem Cifrada.
        this.jTextAreaMensagemCifrada.setText(mensagemCifrada);
    }//GEN-LAST:event_jButtonCifrarActionPerformed

    private void jButtonDecifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecifrarActionPerformed
        
        int chave=7;
        String texto = this.jtMensagem.getText();
	int tamanhoTexto = texto.length();
        StringBuilder textoDecifrado = new StringBuilder();
        
        for(int c=0; c < tamanhoTexto; c++){
			// Transforma o caracter em codigo ASCII e faz a descriptografia
			int letraDecifradaASCII = ((int) texto.charAt(c)) - chave;
			
			// Verifica se o codigo ASCII esta no limite dos caracteres imprimiveis
			while(letraDecifradaASCII < 32)
				letraDecifradaASCII += 94;

			// Transforma codigo ASCII descriptografado em caracter ao novo texto
			textoDecifrado.append( (char)letraDecifradaASCII );
		}
        //converte a mensagem decifrada para String
        String mensagemDecifrada = textoDecifrado.toString();
        //joga a mensagem decifrada na Area de Texto Mensagem Decifrada.
        this.jTextAreaMensagemDecifrada.setText(mensagemDecifrada);
    }//GEN-LAST:event_jButtonDecifrarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterCifra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAbrirImagem;
    private javax.swing.JButton cmdOcultarMensagem;
    private javax.swing.JButton cmdSalvarImagem;
    private javax.swing.JButton cmdVerMensagem;
    private javax.swing.JButton jButtonCifrar;
    private javax.swing.JButton jButtonDecifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaMensagemCifrada;
    private javax.swing.JTextArea jTextAreaMensagemDecifrada;
    private javax.swing.JTextArea jTextAreaMensagemEmClaro;
    private javax.swing.JTextArea jtMensagem;
    // End of variables declaration//GEN-END:variables

}
